package exam09;

public class ExceptionTest {

	public static void main(String[] args) {
		//정상종료 :main에서 시작하여 끝까지 실행되고 종료되는 것.
		System.out.println("1");
		System.out.println("2");
		System.out.println("end. 정상종료");
		
		
	}

}
